version: "3.3"
services:
  gen_electricity_server:
    build: .
    restart: unless-stopped
    image: gen_electricity_server
    container_name: gen_electricity_server_co
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "5011:5011"
