version: "3.3"
services:
  gen_electricity_server:
    build: .
    restart: unless-stopped
    image: gen_electricity_server
    container_name: GenElectricityServer
    env_file: ./.env
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    ports:
      - 5011:5011
